In [61]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [62]:
# diagram show inside jupyter notebook
%matplotlib inline

In [63]:
test_df = pd.read_csv(r'E:\house-prices-advanced-regression-techniques\test.csv')

In [64]:
test_df.head().T

                    0       1       2       3       4
Id               1461    1462    1463    1464    1465
MSSubClass         20      20      60      60     120
MSZoning           RH      RL      RL      RL      RL
LotFrontage      80.0    81.0    74.0    78.0    43.0
LotArea         11622   14267   13830    9978    5005
...               ...     ...     ...     ...     ...
MiscVal             0   12500       0       0       0
MoSold              6       6       3       6       1
YrSold           2010    2010    2010    2010    2010
SaleType           WD      WD      WD      WD      WD
SaleCondition  Normal  Normal  Normal  Normal  Normal

[80 rows x 5 columns]

In [65]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     1443 non-null   object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [66]:
test_df.sort_values(by = 'YearBuilt',inplace = True, ascending = True)
test_df.YearBuilt.head(10)

991     1879
396     1880
962     1890
636     1890
78      1890
646     1890
329     1890
757     1895
1119    1895
966     1895
Name: YearBuilt, dtype: int64

In [67]:
test_df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
991,2452,75,RM,75.0,13500,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,2,2007,WD,Normal
396,1857,70,RL,120.0,26400,Pave,NaN,Reg,Bnk,AllPub,...,0,0,NaN,NaN,NaN,0,6,2009,WD,Normal
962,2423,50,RL,60.0,14190,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2007,WD,Normal
636,2097,50,RM,44.0,5914,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
78,1539,70,RM,50.0,9000,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,1662,60,RL,95.0,12350,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2009,New,Partial
112,1573,20,RL,44.0,17485,Pave,NaN,IR2,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2010,Con,Partial
148,1609,20,RL,73.0,9803,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2010,New,Partial
116,1577,20,RL,64.0,7360,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2010,WD,Normal
42,1503,20,FV,57.0,12853,Pave,Pave,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,New,Partial

In [68]:
# find numerical null values
for label , content in test_df.items():
    if pd.api.types.is_numeric_dtype(content):
        if pd.isnull(content).sum():
            print(label)

LotFrontage
MasVnrArea
BsmtFinSF1
BsmtFinSF2
BsmtUnfSF
TotalBsmtSF
BsmtFullBath
BsmtHalfBath
GarageYrBlt
GarageCars
GarageArea

In [69]:
# fill numerical columns
test_df['MasVnrArea'].fillna(test_df.MasVnrArea.median(),inplace =True)
test_df['GarageYrBlt'].fillna(test_df['YearBuilt'],inplace =True)
test_df['LotFrontage'].fillna(test_df['LotFrontage'].median(),inplace =True)
test_df['GarageArea'].fillna(0.0,inplace =True)
test_df['GarageCars'].fillna(0.0,inplace =True)
test_df['BsmtHalfBath'].fillna(0.0,inplace =True)
test_df['BsmtFullBath'].fillna(0.0,inplace =True)
test_df['TotalBsmtSF'].fillna(0.0,inplace =True)
test_df['BsmtFinSF1'].fillna(0.0,inplace =True)
test_df['BsmtFinSF2'].fillna(0.0,inplace =True)
test_df['BsmtUnfSF'].fillna(0.0,inplace =True)

In [70]:
# find anu more null values numerical column
for label , content in test_df.items():
    if pd.api.types.is_numeric_dtype(content):
        if pd.isnull(content).sum():
            print(label)

In [71]:
# non_numeric null values
for label , content in test_df.items():
    if pd.api.types.is_string_dtype(content):
        if pd.isnull(content).sum():
           print(label)

MSZoning
Alley
Utilities
Exterior1st
Exterior2nd
MasVnrType
BsmtQual
BsmtCond
BsmtExposure
BsmtFinType1
BsmtFinType2
KitchenQual
Functional
FireplaceQu
GarageType
GarageFinish
GarageQual
GarageCond
PoolQC
Fence
MiscFeature
SaleType

In [72]:
# fill null values of non-numerric data type
test_df['Alley'].fillna('No alley access',inplace =True)
test_df['MasVnrType'].fillna(test_df.MasVnrType.mode()[0],inplace =True)
test_df['BsmtQual'].fillna('No Basement',inplace =True)
test_df['BsmtCond'].fillna('No Basement',inplace =True)
test_df['BsmtExposure'].fillna('No Basement',inplace =True)
test_df['BsmtFinType1'].fillna('No Basement',inplace =True)
test_df['BsmtFinType2'].fillna('No Basement',inplace =True)
test_df['Electrical'].fillna(test_df['Electrical'].mode()[0],inplace =True)
test_df['FireplaceQu'].fillna('No Fireplace',inplace =True)
test_df['GarageType'].fillna('No Garage',inplace =True)
test_df['GarageFinish'].fillna('No Garage',inplace =True)
test_df['GarageQual'].fillna('No Garage',inplace =True)
test_df['GarageCond'].fillna('No Garage',inplace =True)
test_df['PoolQC'].fillna('No Pool',inplace =True)
test_df['Fence'].fillna('No Fence',inplace =True)
test_df['MSZoning'].fillna('RL',inplace =True)
test_df['Utilities'].fillna('AllPub',inplace =True)
test_df['Exterior1st'].fillna('VinylSd',inplace =True)
test_df['Exterior2nd'].fillna('VinylSd',inplace =True)
test_df['KitchenQual'].fillna('TA',inplace =True)
test_df['Functional'].fillna('Typ',inplace =True)
test_df['SaleType'].fillna('WD',inplace =True)
test_df['MiscFeature'].fillna('None',inplace =True)

In [73]:
# any more null values in non_numeric columns
for label , content in test_df.items():
    if pd.api.types.is_string_dtype(content):
        if pd.isnull(content).sum():
           print(label)

In [74]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 991 to 42
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1459 non-null   object
 3   LotFrontage    1459 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          1459 non-null   object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1459 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1459 non-null   object
 24  Exterior2nd    1459 non-null   object
 25  MasVnrType     1459 non-null   object
 26  MasVnrArea     1459 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1459 non-null   object
 31  BsmtCond       1459 non-null   object
 32  BsmtExposure   1459 non-null   object
 33  BsmtFinType1   1459 non-null   object
 34  BsmtFinSF1     1459 non-null   float64
 35  BsmtFinType2   1459 non-null   object
 36  BsmtFinSF2     1459 non-null   float64
 37  BsmtUnfSF      1459 non-null   float64
 38  TotalBsmtSF    1459 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1459 non-null   float64
 48  BsmtHalfBath   1459 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1459 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1459 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    1459 non-null   object
 58  GarageType     1459 non-null   object
 59  GarageYrBlt    1459 non-null   float64
 60  GarageFinish   1459 non-null   object
 61  GarageCars     1459 non-null   float64
 62  GarageArea     1459 non-null   float64
 63  GarageQual     1459 non-null   object
 64  GarageCond     1459 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         1459 non-null   object
 73  Fence          1459 non-null   object
 74  MiscFeature    1459 non-null   object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1459 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 923.3+ KB

In [75]:
# convert object data into catogory and then in numbers
for label , content in test_df.items():
    if not pd.api.types.is_numeric_dtype(content):
        # conert string data into category
        test_df[label] = content.astype('category').cat.as_ordered()
        
        # turn categorical data into numbers
        test_df[label] = pd.Categorical(content).codes

In [76]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 991 to 42
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1459 non-null   int8
 3   LotFrontage    1459 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   int8
 6   Alley          1459 non-null   int8
 7   LotShape       1459 non-null   int8
 8   LandContour    1459 non-null   int8
 9   Utilities      1459 non-null   int8
 10  LotConfig      1459 non-null   int8
 11  LandSlope      1459 non-null   int8
 12  Neighborhood   1459 non-null   int8
 13  Condition1     1459 non-null   int8
 14  Condition2     1459 non-null   int8
 15  BldgType       1459 non-null   int8
 16  HouseStyle     1459 non-null   int8
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   int8
 22  RoofMatl       1459 non-null   int8
 23  Exterior1st    1459 non-null   int8
 24  Exterior2nd    1459 non-null   int8
 25  MasVnrType     1459 non-null   int8
 26  MasVnrArea     1459 non-null   float64
 27  ExterQual      1459 non-null   int8
 28  ExterCond      1459 non-null   int8
 29  Foundation     1459 non-null   int8
 30  BsmtQual       1459 non-null   int8
 31  BsmtCond       1459 non-null   int8
 32  BsmtExposure   1459 non-null   int8
 33  BsmtFinType1   1459 non-null   int8
 34  BsmtFinSF1     1459 non-null   float64
 35  BsmtFinType2   1459 non-null   int8
 36  BsmtFinSF2     1459 non-null   float64
 37  BsmtUnfSF      1459 non-null   float64
 38  TotalBsmtSF    1459 non-null   float64
 39  Heating        1459 non-null   int8
 40  HeatingQC      1459 non-null   int8
 41  CentralAir     1459 non-null   int8
 42  Electrical     1459 non-null   int8
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1459 non-null   float64
 48  BsmtHalfBath   1459 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1459 non-null   int8
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1459 non-null   int8
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    1459 non-null   int8
 58  GarageType     1459 non-null   int8
 59  GarageYrBlt    1459 non-null   float64
 60  GarageFinish   1459 non-null   int8
 61  GarageCars     1459 non-null   float64
 62  GarageArea     1459 non-null   float64
 63  GarageQual     1459 non-null   int8
 64  GarageCond     1459 non-null   int8
 65  PavedDrive     1459 non-null   int8
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         1459 non-null   int8
 73  Fence          1459 non-null   int8
 74  MiscFeature    1459 non-null   int8
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1459 non-null   int8
 79  SaleCondition  1459 non-null   int8
dtypes: float64(11), int64(26), int8(43)
memory usage: 494.4 KB

In [77]:
test_df.shape

(1459, 80)

In [78]:
test_df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
991,2452,75,4,75.0,13500,1,0,3,3,0,...,0,0,2,2,1,0,2,2007,8,4
396,1857,70,3,120.0,26400,1,1,3,0,0,...,0,0,2,4,1,0,6,2009,8,4
962,2423,50,3,60.0,14190,1,1,3,3,0,...,0,0,2,4,1,0,4,2007,8,4
636,2097,50,4,44.0,5914,1,0,3,3,0,...,0,0,2,4,1,0,9,2008,8,4
78,1539,70,4,50.0,9000,1,0,3,3,0,...,0,0,2,4,1,0,4,2010,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,1662,60,3,95.0,12350,1,1,3,3,0,...,0,0,2,4,1,0,7,2009,6,5
112,1573,20,3,44.0,17485,1,1,1,3,0,...,0,0,2,4,1,0,1,2010,2,5
148,1609,20,3,73.0,9803,1,1,3,3,0,...,0,0,2,4,1,0,1,2010,6,5
116,1577,20,3,64.0,7360,1,1,3,3,0,...,0,0,2,4,1,0,3,2010,8,4
42,1503,20,1,57.0,12853,1,2,0,3,0,...,0,0,2,4,1,0,4,2010,6,5

In [79]:
# export data into new_test_df csv file
test_df.to_csv('new_test_df.csv',index =False)